name: Compile changelog

permissions:
  contents: write

on:
  workflow_dispatch: # this workflow can only be manually triggered, see update_changelog.yml for full flow

jobs:
  CompileCL:
    permissions:
      contents: write # required to push the updated changelog commit
    runs-on: ubuntu-22.04
    steps:
      - name: "Check for BOT_TOKEN_AURORA secret and pass true to output if it exists to be checked by later steps"
        id: value_holder
        env:
          ENABLER_SECRET: ${{ secrets.BOT_TOKEN_AURORA }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "ACTIONS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: master
          persist-credentials: false
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix
      - name: Compile CL
        run: |
          python tools/ss13_genchangelog.py html/changelogs
      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Changelogs""
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Automatic changelog generation [ci skip]" -a
          git push
