name: "Build Changelog"
on:
  push:
    branches:
      - auto_changelog

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  MakeCL:
    name: "Make Changelogs"
    permissions:
      contents: write # required to push the changelog chunk yml commit
    runs-on: ubuntu-24.04
    steps:
      - name: "Check for BOT_TOKEN_AURORA secret and pass true to output if it exists to be checked by later steps"
        id: value_holder
        env:
          ENABLER_SECRET: ${{ secrets.BOT_TOKEN_AURORA }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "ACTIONS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: "Checkout"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get PR number
        id: pr
        run: |
          PR_NUM=$(gh pr list --search ${{ github.sha }} --state merged --json number -q '.[] | .number' || echo "")
          echo "PR number: $PR_NUM"
          echo "pull_request_number=$PR_NUM" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup python"
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: "Install deps"
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix
      - name: Make CL
        env:
          BOT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR: "${{ steps.pr.outputs.pull_request_number }}"
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
        run: python tools/changelog/generate_cl.py
      - name: List CL files
        id: cl_files
        run: |
          CL_FILES=$(ls html/changelogs | grep -vwE 'example.yml|__CHANGELOG_README.txt' | wc -l || '0')
          echo "Number of changelog files: $CL_FILES"
          echo "cl_files=$CL_FILES" >> $GITHUB_OUTPUT
        if: ${{ steps.pr.outputs.pull_request_number != '' }}
      - name: "Compile CL"
        if: steps.value_holder.outputs.ACTIONS_ENABLED
        run: |
          tools/bootstrap/python tools/changelog/ss13_genchangelog.py html/changelogs
      - name: Commit
        env:
          PR_NUMBER: ${{ steps.pr.outputs.pull_request_number }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Changelogs"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git add html/changelogs
          git commit -m "Automatic changelog generation for PR #$PR_NUMBER [ci skip]" -a || true
        if: ${{ steps.cl_files.outputs.cl_files != '0' }}
      - name: "Push"
        if: ${{ steps.cl_files.outputs.cl_files != '0' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN_AURORA || secrets.GITHUB_TOKEN }}
